# Generated by Django 5.2.3 on 2025-06-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta_sql', models.TextField()),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
    ]
