# Generated by Django 5.2.3 on 2025-06-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredenciaisHubsoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('client_id', models.CharField(max_length=100, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=100, verbose_name='Client Secret')),
                ('username', models.EmailField(max_length=254, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('url_base', models.URLField(verbose_name='URL Base')),
                ('url_token', models.URLField(verbose_name='URL Token')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Credencial Hubsoft',
                'verbose_name_plural': 'Credenciais Hubsoft',
            },
        ),
    ]
