# Generated by Django 5.2.3 on 2025-06-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_credenciaishubsoft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteConsultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(max_length=50, verbose_name='Código do Cliente')),
                ('nome_razaosocial', models.CharField(max_length=255, verbose_name='Nome/Razão Social')),
                ('telefone_corrigido', models.CharField(max_length=20, verbose_name='Telefone Corrigido')),
                ('id_fatura', models.CharField(max_length=50, verbose_name='ID da Fatura')),
            ],
            options={
                'verbose_name': 'Cliente Consultado',
                'verbose_name_plural': 'Clientes Consultados',
            },
        ),
        migrations.CreateModel(
            name='ConsultaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Consulta')),
                ('data_consulta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Consulta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanhas.clienteconsultado', verbose_name='Cliente')),
                ('template_sql', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanhas.templatesql', verbose_name='Template SQL')),
            ],
            options={
                'verbose_name': 'Consulta de Cliente',
                'verbose_name_plural': 'Consultas de Clientes',
                'ordering': ['-data_consulta'],
            },
        ),
    ]
