# Generated by Django 5.2.3 on 2025-06-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0003_clienteconsultado_consultacliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteconsultado',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='clienteconsultado',
            name='link_boleto',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Boleto'),
        ),
        migrations.AddField(
            model_name='clienteconsultado',
            name='pix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código PIX'),
        ),
        migrations.AddField(
            model_name='clienteconsultado',
            name='valor_fatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Fatura'),
        ),
        migrations.AddField(
            model_name='clienteconsultado',
            name='vencimento_fatura',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento da Fatura'),
        ),
        migrations.AlterField(
            model_name='clienteconsultado',
            name='id_fatura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID da Fatura'),
        ),
    ]
