# Generated by Django 5.2.3 on 2025-06-17 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0004_clienteconsultado_codigo_barras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredenciaisBancoDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('tipo_banco', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('sqlserver', 'SQL Server'), ('oracle', 'Oracle')], max_length=20, verbose_name='Tipo de Banco')),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('porta', models.IntegerField(verbose_name='Porta')),
                ('banco', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuário')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Credencial de Banco de Dados',
                'verbose_name_plural': 'Credenciais de Banco de Dados',
            },
        ),
        migrations.AlterModelOptions(
            name='templatesql',
            options={'verbose_name': 'Template SQL', 'verbose_name_plural': 'Templates SQL'},
        ),
        migrations.AddField(
            model_name='clienteconsultado',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='clienteconsultado',
            name='data_criacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='consultacliente',
            name='dados_api_response',
            field=models.JSONField(blank=True, help_text='Dados retornados da API', null=True, verbose_name='Resposta da API'),
        ),
        migrations.AddField(
            model_name='consultacliente',
            name='dados_originais_sql',
            field=models.JSONField(blank=True, help_text='Dados retornados da consulta SQL', null=True, verbose_name='Dados Originais SQL'),
        ),
        migrations.AddField(
            model_name='consultacliente',
            name='erro_api',
            field=models.TextField(blank=True, null=True, verbose_name='Erro da API'),
        ),
        migrations.AddField(
            model_name='consultacliente',
            name='sucesso_api',
            field=models.BooleanField(default=False, verbose_name='Sucesso na API'),
        ),
        migrations.AddField(
            model_name='credenciaishubsoft',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='templatesql',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='templatesql',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='templatesql',
            name='data_criacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='templatesql',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='clienteconsultado',
            name='codigo_cliente',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código do Cliente'),
        ),
        migrations.AlterField(
            model_name='clienteconsultado',
            name='telefone_corrigido',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Corrigido'),
        ),
        migrations.AlterField(
            model_name='templatesql',
            name='consulta_sql',
            field=models.TextField(verbose_name='Consulta SQL'),
        ),
        migrations.AlterField(
            model_name='templatesql',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='ConsultaExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Execução')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Executando'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status')),
                ('total_registros_sql', models.IntegerField(default=0, verbose_name='Total de Registros SQL')),
                ('total_consultados_api', models.IntegerField(default=0, verbose_name='Total Consultados API')),
                ('total_erros', models.IntegerField(default=0, verbose_name='Total de Erros')),
                ('log_execucao', models.TextField(blank=True, null=True, verbose_name='Log de Execução')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('credencial_hubsoft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanhas.credenciaishubsoft', verbose_name='Credencial Hubsoft')),
                ('template_sql', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanhas.templatesql', verbose_name='Template SQL')),
                ('credencial_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanhas.credenciaisbancodados', verbose_name='Credencial Banco de Dados')),
            ],
            options={
                'verbose_name': 'Execução de Consulta',
                'verbose_name_plural': 'Execuções de Consultas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='consultacliente',
            name='execucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campanhas.consultaexecucao', verbose_name='Execução'),
        ),
        migrations.AlterUniqueTogether(
            name='consultacliente',
            unique_together={('execucao', 'cliente')},
        ),
        migrations.RemoveField(
            model_name='consultacliente',
            name='template_sql',
        ),
        migrations.RemoveField(
            model_name='consultacliente',
            name='titulo',
        ),
    ]
