# Generated by Django 5.2.3 on 2025-06-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0005_credenciaisbancodados_alter_templatesql_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaexecucao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Executando'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
