# Generated by Django 5.2.3 on 2025-06-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0006_alter_consultaexecucao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaexecucao',
            name='valor_total_faturas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total das Faturas'),
        ),
    ]
