# Generated by Django 5.2.3 on 2025-06-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0007_consultaexecucao_valor_total_faturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultaexecucao',
            name='valor_total_faturas',
        ),
    ]
