# Generated by Django 5.2.3 on 2025-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0008_remove_consultaexecucao_valor_total_faturas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome para identificar esta configuração', max_length=100, verbose_name='Nome da Configuração')),
                ('base_url', models.URLField(help_text='URL base da API Matrix (ex: https://megalink.matrixdobrasil.ai)', verbose_name='URL Base da API')),
                ('api_key', models.CharField(help_text='Chave de autenticação da API Matrix', max_length=255, verbose_name='Chave da API')),
                ('cod_conta', models.IntegerField(help_text='Código da conta na Matrix', verbose_name='Código da Conta')),
                ('ativo', models.BooleanField(default=True, help_text='Se esta configuração está ativa', verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Configuração da API Matrix',
                'verbose_name_plural': 'Configurações da API Matrix',
                'ordering': ['-ativo', 'nome'],
            },
        ),
    ]
