# Generated by Django 5.2.3 on 2025-06-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0009_matrixapiconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSMTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo do template HSM', max_length=200, verbose_name='Nome do Template')),
                ('hsm_id', models.IntegerField(help_text='ID do template HSM na Matrix', verbose_name='ID do HSM')),
                ('cod_flow', models.IntegerField(blank=True, help_text='Código do flow de atendimento', null=True, verbose_name='Código do Flow')),
                ('tipo_envio', models.IntegerField(choices=[(1, 'Atendimento Automático'), (2, 'Notificação'), (3, 'Fila de Atendimento')], default=1, help_text='Tipo de envio do HSM', verbose_name='Tipo de Envio')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do template', verbose_name='Descrição')),
                ('variaveis_descricao', models.JSONField(blank=True, default=dict, help_text="Descrição das variáveis do HSM (ex: {'1': 'Nome do Cliente', '2': 'Valor'})", verbose_name='Descrição das Variáveis')),
                ('ativo', models.BooleanField(default=True, help_text='Se este template está ativo', verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Template HSM',
                'verbose_name_plural': 'Templates HSM',
                'ordering': ['nome'],
            },
        ),
    ]
