# Generated by Django 5.2.4 on 2025-07-11 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0010_hsmtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaexecucao',
            name='valores_variaveis',
            field=models.JSONField(blank=True, default=dict, help_text='Valores fornecidos pelo usuário para as variáveis do template', null=True, verbose_name='Valores das Variáveis'),
        ),
        migrations.AddField(
            model_name='templatesql',
            name='variaveis_config',
            field=models.JSONField(blank=True, default=dict, help_text="Configuração das variáveis no formato: {'var_name': {'tipo': 'text', 'label': 'Label', 'obrigatorio': True, 'valor_padrao': '', 'opcoes': []}}", null=True, verbose_name='Configuração das Variáveis'),
        ),
        migrations.CreateModel(
            name='VariavelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome usado no SQL: {{nome_da_variavel}}', max_length=100, verbose_name='Nome da Variável')),
                ('label', models.CharField(help_text='Texto exibido no formulário para o usuário', max_length=200, verbose_name='Rótulo')),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('datetime', 'Data e Hora'), ('select', 'Lista de Opções')], default='text', max_length=20, verbose_name='Tipo do Campo')),
                ('obrigatorio', models.BooleanField(default=True, help_text='Se o campo deve ser preenchido obrigatoriamente', verbose_name='Obrigatório')),
                ('valor_padrao', models.CharField(blank=True, help_text='Valor pré-preenchido no formulário', max_length=500, verbose_name='Valor Padrão')),
                ('opcoes', models.TextField(blank=True, help_text="Para tipo 'Lista de Opções': uma opção por linha", verbose_name='Opções')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição no formulário', verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('template_sql', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaveis', to='campanhas.templatesql', verbose_name='Template SQL')),
            ],
            options={
                'verbose_name': 'Variável do Template',
                'verbose_name_plural': 'Variáveis do Template',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('template_sql', 'nome')},
            },
        ),
    ]
