# Generated by Django 5.2.4 on 2025-07-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0011_consultaexecucao_valores_variaveis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioHSMMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descritivo para identificar este envio', max_length=255, verbose_name='Título do Envio')),
                ('status_envio', models.CharField(choices=[('pendente', 'Pendente'), ('enviando', 'Enviando'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('erro', 'Erro'), ('pausado', 'Pausado')], default='pendente', max_length=20, verbose_name='Status do Envio')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_inicio_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início do Envio')),
                ('data_fim_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim do Envio')),
                ('total_clientes', models.IntegerField(default=0, verbose_name='Total de Clientes')),
                ('total_enviados', models.IntegerField(default=0, verbose_name='Total Enviados')),
                ('total_erros', models.IntegerField(default=0, verbose_name='Total de Erros')),
                ('total_pendentes', models.IntegerField(default=0, verbose_name='Total Pendentes')),
                ('log_execucao', models.TextField(blank=True, help_text='Log detalhado da execução do envio', null=True, verbose_name='Log de Execução')),
                ('configuracao_variaveis', models.JSONField(blank=True, default=dict, help_text='Mapeamento das variáveis do HSM com campos dos dados', verbose_name='Configuração das Variáveis')),
                ('filtros_adicionais', models.JSONField(blank=True, default=dict, help_text='Filtros adicionais para seleção de clientes', verbose_name='Filtros Adicionais')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('consulta_execucao', models.ForeignKey(blank=True, help_text='Execução da consulta que fornecerá os dados para envio', null=True, on_delete=django.db.models.deletion.CASCADE, to='campanhas.consultaexecucao', verbose_name='Execução da Consulta')),
                ('hsm_template', models.ForeignKey(help_text='Template HSM que será enviado', on_delete=django.db.models.deletion.CASCADE, to='campanhas.hsmtemplate', verbose_name='Template HSM')),
                ('matrix_api_config', models.ForeignKey(help_text='Configuração da API Matrix para envio', on_delete=django.db.models.deletion.CASCADE, to='campanhas.matrixapiconfig', verbose_name='Configuração da API Matrix')),
            ],
            options={
                'verbose_name': 'Envio HSM Matrix',
                'verbose_name_plural': 'Envios HSM Matrix',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='EnvioHSMIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data do Envio')),
                ('resposta_api', models.JSONField(blank=True, help_text='Resposta completa da API Matrix', null=True, verbose_name='Resposta da API')),
                ('erro_detalhado', models.TextField(blank=True, help_text='Detalhes do erro caso ocorra', null=True, verbose_name='Erro Detalhado')),
                ('tentativas', models.PositiveIntegerField(default=0, verbose_name='Tentativas de Envio')),
                ('variaveis_utilizadas', models.JSONField(blank=True, default=dict, help_text='Variáveis que foram utilizadas no envio', verbose_name='Variáveis Utilizadas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanhas.clienteconsultado', verbose_name='Cliente')),
                ('envio_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_individuais', to='campanhas.enviohsmmatrix', verbose_name='Envio Matrix')),
            ],
            options={
                'verbose_name': 'Envio HSM Individual',
                'verbose_name_plural': 'Envios HSM Individuais',
                'ordering': ['-data_envio'],
                'unique_together': {('envio_matrix', 'cliente')},
            },
        ),
    ]
