# Generated by Django 5.2.4 on 2025-07-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0012_enviohsmmatrix_enviohsmindividual'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteconsultado',
            name='credencial_banco',
            field=models.ForeignKey(blank=True, help_text='Identifica de qual base/empresa este cliente foi consultado', null=True, on_delete=django.db.models.deletion.CASCADE, to='campanhas.credenciaisbancodados', verbose_name='Credencial de Banco'),
        ),
        migrations.AlterField(
            model_name='clienteconsultado',
            name='codigo_cliente',
            field=models.CharField(max_length=50, verbose_name='Código do Cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='clienteconsultado',
            unique_together={('codigo_cliente', 'credencial_banco')},
        ),
    ]
