# Generated by Django 5.2.4 on 2025-08-01 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0013_clienteconsultado_credencial_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='configuracao_variaveis_contingencia',
            field=models.JSONField(blank=True, default=dict, help_text='Mapeamento das variáveis do HSM de contingência com campos dos dados', verbose_name='Configuração das Variáveis - Contingência'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='hsm_template_contingencia',
            field=models.ForeignKey(blank=True, help_text='Template HSM alternativo usado quando alguma variável do template principal estiver vazia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_contingencia', to='campanhas.hsmtemplate', verbose_name='Template HSM de Contingência'),
        ),
        migrations.AlterField(
            model_name='enviohsmmatrix',
            name='hsm_template',
            field=models.ForeignKey(help_text='Template HSM principal que será enviado quando todas as variáveis estiverem preenchidas', on_delete=django.db.models.deletion.CASCADE, to='campanhas.hsmtemplate', verbose_name='Template HSM Principal'),
        ),
    ]
