# Generated by Django 5.2.4 on 2025-08-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0014_enviohsmmatrix_configuracao_variaveis_contingencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviohsmindividual',
            name='template_usado',
            field=models.CharField(choices=[('principal', 'Principal'), ('contingencia', 'Contingência')], default='principal', help_text='Indica se foi usado o template principal ou de contingência', max_length=20, verbose_name='Template Usado'),
        ),
    ]
